import { Montserrat_Alternates } from "next/font/google";
import "../../styles/globals.scss";
import Head from "next/head";

const montserratAlternates = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata = {
  title: "Ninja Drive Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/logo192.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/logo32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/logo16.png" />
      </Head>
      <body className={montserratAlternates.className}>{children}</body>
    </html>
  );
}
